<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>CK2 script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:character_event|on_startup)\s*(?=\=)</string>
			<key>name</key>
			<string>comment.block.sass</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.sass.ck2_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ck2_script</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.object.ck2_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(namespace)\s*(=)\s*([a-zA-Z_]+)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#values</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>clause</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>commands</key>
		<dict>
			<key>match</key>
			<string>\b(?:add_claim|add_friend)\b</string>
			<key>name</key>
			<string>entity.other.inherited-class.ck2_script</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.ck2_script</string>
		</dict>
		<key>conditionoperators</key>
		<dict>
			<key>match</key>
			<string>\b(?:AND|OR|NOT|NOR|NAND|calc_true_if)\b</string>
			<key>name</key>
			<string>variable.parameter.function.language</string>
		</dict>
		<key>conditions</key>
		<dict>
			<key>match</key>
			<string>\b(?:age|ai)\b</string>
			<key>name</key>
			<string>variable.parameter.function.language</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.deprecated.ck2_script</string>
		</dict>
		<key>keys</key>
		<dict>
			<key>begin</key>
			<string>\s*(?=[\w])</string>
			<key>end</key>
			<string>\s*(?=\W)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#specialscopes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scopes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditionoperators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>match</key>
			<string>\b(?:id|desc|picture|is_triggered_only|option|name)\b</string>
			<key>name</key>
			<string>meta.diff.range.unified</string>
		</dict>
		<key>scopes</key>
		<dict>
			<key>match</key>
			<string>\b(?:any_allied_character|any_friend)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.placeholder-selector.sass</string>
		</dict>
		<key>specialscopes</key>
		<dict>
			<key>match</key>
			<string>\b(?:ROOT|FROM|PREV|THIS|)\b</string>
			<key>name</key>
			<string>keyword.other.ck2_script</string>
		</dict>
		<key>values</key>
		<dict>
			<key>begin</key>
			<string>\s*(=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ck2_script</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=[^\s=])\s*(?=[\W])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:yes|no)\b</string>
					<key>name</key>
					<string>constant.language.ck2_script</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.ck2_script</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#specialscopes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#clause</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:EVT(?:DESC|OPT)[\w\.]*|OK)\b</string>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
				<dict>
					<key>match</key>
					<string>GFX[\w\.]*\b</string>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.object.ck2_script</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.ck2_script</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.ck2_script</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\w+)(\.)(\d+)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>variable.other.constant.ck2_script</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ck2_script</string>
	<key>uuid</key>
	<string>a69eb4bc-df5a-4ec9-beae-c7c0f2a95143</string>
</dict>
</plist>
